class DemoData {
  static const List<Map<String, dynamic>> sampleJobs = [
    {
      'id': 'job_001',
      'employerUid': 'demo_emp_1',
      'employerName': 'Metro Build Co.',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Metro+Build&background=1D4ED8&color=fff&size=128',
      'title': 'Maintenance Technician',
      'description': 'Looking for an experienced maintenance technician for residential projects. Must have general repair skills and basic knowledge of electrical systems.',
      'category': 'blue_collar',
      'location': 'Mumbai',
      'salary': {'min': 15000, 'max': 22000, 'type': 'monthly'},
      'skillsRequired': ['General Repair', 'Plumbing', 'Basic Electrical', 'Tool Handling'],
      'jobType': 'full_time',
      'isActive': true,
      'postedDaysAgo': 1,
      'applicantCount': 5,
    },
    {
      'id': 'job_002',
      'employerUid': 'demo_emp_2',
      'employerName': 'CleanHome Services',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Clean+Home&background=059669&color=fff&size=128',
      'title': 'Housekeeping Supervisor',
      'description': 'Monitor and coordinate housekeeping staff for a premium gated community. Ensure high standards of cleanliness and safety.',
      'category': 'blue_collar',
      'location': 'Bangalore',
      'salary': {'min': 15000, 'max': 20000, 'type': 'monthly'},
      'skillsRequired': ['Deep Cleaning', 'Supervision', 'Inventory Management'],
      'jobType': 'full_time',
      'isActive': true,
      'postedDaysAgo': 2,
      'applicantCount': 8,
    },
    {
      'id': 'job_003',
      'employerUid': 'demo_emp_3',
      'employerName': 'Mehta & Associates',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Mehta+Associates&background=6D4C41&color=fff&size=128',
      'title': 'Tally Accountant',
      'description': 'Requirement for an accountant proficient in Tally Prime, GST filing, and monthly closing. Work from office, Mumbai location.',
      'category': 'white_collar',
      'location': 'Mumbai',
      'salary': {'min': 22000, 'max': 30000, 'type': 'monthly'},
      'skillsRequired': ['Tally', 'MS Excel', 'GST Filing', 'Bank Reconciliation'],
      'jobType': 'full_time',
      'isActive': true,
      'postedDaysAgo': 3,
      'applicantCount': 12,
    },
    {
      'id': 'job_004',
      'employerUid': 'demo_emp_4',
      'employerName': 'Rajasthan Pipes & Fittings',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Rajasthan+Pipes&background=EF6C00&color=fff&size=128',
      'title': 'Experienced Plumber',
      'description': 'Need a skilled plumber for factory maintenance and residential plumbing projects in Jaipur. CPVC and UPVC fitting experience required.',
      'category': 'blue_collar',
      'location': 'Jaipur',
      'salary': {'min': 500, 'max': 800, 'type': 'daily'},
      'skillsRequired': ['CPVC Fitting', 'Drainage', 'Sanitary Work', 'UPVC Pipes'],
      'jobType': 'contract',
      'isActive': true,
      'postedDaysAgo': 0,
      'applicantCount': 1,
    },
    {
      'id': 'job_005',
      'employerUid': 'demo_emp_1',
      'employerName': 'Metro Build Co.',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Metro+Build&background=1D4ED8&color=fff&size=128',
      'title': 'Security Guard',
      'description': 'Reliable security personnel needed for night shifts. Should have basic self-defense training and good observation skills.',
      'category': 'blue_collar',
      'location': 'Mumbai',
      'salary': {'min': 14000, 'max': 16000, 'type': 'monthly'},
      'skillsRequired': ['Surveillance', 'Gate Management', 'NOC Verification'],
      'jobType': 'full_time',
      'isActive': true,
      'postedDaysAgo': 4,
      'applicantCount': 22,
    },
    {
      'id': 'job_006',
      'employerUid': 'demo_emp_5',
      'employerName': 'TechSpark Solutions',
      'employerLogoUrl': 'https://ui-avatars.com/api/?name=Tech+Spark&background=4F46E5&color=fff&size=128',
      'title': 'Data Entry Operator',
      'description': 'Fast typing skills and attention to detail required for customer data logging. Hybrid work available after 1 month.',
      'category': 'white_collar',
      'location': 'Delhi',
      'salary': {'min': 12000, 'max': 15000, 'type': 'monthly'},
      'skillsRequired': ['Typing Speed', 'Accuracy', 'Google Sheets'],
      'jobType': 'full_time',
      'isActive': true,
      'postedDaysAgo': 1,
      'applicantCount': 45,
    },
  ];

  static const List<Map<String, dynamic>> sampleEmployers = [
    {
      'uid': 'demo_emp_1',
      'companyName': 'Metro Build Co.',
      'businessType': 'Private Limited',
      'location': 'Mumbai',
      'logoUrl': 'https://ui-avatars.com/api/?name=Metro+Build&background=1D4ED8&color=fff&size=128',
      'description': 'A leading infrastructure and construction firm with over 20 years of excellence in building residential landmarks across North Mumbai.',
      'contactPersonName': 'Prasanna Kumar',
      'isVerified': true,
    },
    {
      'uid': 'demo_emp_2',
      'companyName': 'CleanHome Services',
      'businessType': 'Partnership',
      'location': 'Bangalore',
      'logoUrl': 'https://ui-avatars.com/api/?name=Clean+Home&background=059669&color=fff&size=128',
      'description': 'Professional home cleaning and facility management experts serving major cities in India.',
      'contactPersonName': 'Arun Varma',
      'isVerified': true,
    },
  ];
}
